apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-infisical-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: portfolio-monitoring
    app.kubernetes.io/managed-by: argocd
spec:
  hostAPI: https://app.infisical.com/api

  resyncInterval: 60

  authentication:
    universalAuth:
      secretsScope:
        projectSlug:  "REPLACE_WITH_YOUR_PROJECT_SLUG"
        envSlug:      "dev"
        secretsPath:  "/monitoring/grafana"
      credentialsRef:
        secretName:      infisical-machine-identity
        secretNamespace: monitoring

  managedSecretReference:
    secretName:      grafana-admin-secret
    secretNamespace: monitoring
    creationPolicy:  Orphan
