apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: portfolio-monitoring
    app.kubernetes.io/component: alerting
    app.kubernetes.io/managed-by: argocd
