apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: portfolio-monitoring
    app.kubernetes.io/component: alerting
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
      protocol: TCP
