apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: portfolio-monitoring
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: argocd
spec:
  type: ClusterIP
  selector:
    app: postgres-exporter
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
      protocol: TCP
